# Generated by Django 5.2.8 on 2025-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cabinet_secretary', 'Cabinet Secretary'), ('county_director', 'County Director'), ('subcounty_director', 'Subcounty Director'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('learner', 'Learner')], default='teacher', max_length=50),
        ),
    ]
