# Generated by Django 5.2.8 on 2025-11-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('cabinet_secretary', 'Cabinet Secretary'), ('county_director', 'County Director'), ('subcounty_director', 'Subcounty Director'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('learner', 'Learner')], default='teacher', max_length=50, null=True),
        ),
    ]
