# Generated by Django 5.2.8 on 2025-11-12 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('birth_certificate_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('grade', models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=20)),
                ('year', models.IntegerField(default=2025)),
                ('admission_date', models.DateField(default=datetime.date.today)),
                ('profile_image', models.ImageField(blank=True, help_text='Optional profile image for the learner.', null=True, upload_to='learner_profiles/')),
                ('parent_full_name', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(max_length=15)),
                ('relationship_to_learner', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian'), ('Other', 'Other')], max_length=50)),
                ('postal_address', models.CharField(help_text='e.g. P.O. Box 36 Bomet', max_length=100)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_learners', to='teachers.teacher')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.county')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.subcounty')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Compulsory subjects are auto-assigned; optional subjects can be selected here', related_name='learners', to='subjects.subject')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.ward')),
            ],
            options={
                'verbose_name': 'Learner',
                'verbose_name_plural': 'Learners',
                'ordering': ['school', 'grade', 'last_name', 'first_name'],
            },
        ),
    ]
