# Generated by Django 5.2.8 on 2025-11-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('school_level', models.CharField(choices=[('PrePrimary', 'Pre-Primary'), ('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.county')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.subcounty')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.ward')),
            ],
        ),
    ]
