# Generated by Django 5.2.8 on 2025-11-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade_level', models.CharField(choices=[('PrePrimary', 'Pre-Primary (PP1-PP2)'), ('LowerPrimary', 'Lower Primary (Grade 1-3)'), ('UpperPrimary', 'Upper Primary (Grade 4-6)'), ('JuniorSecondary', 'Junior Secondary (Grade 7-9)'), ('SeniorSecondary', 'Senior Secondary (Grade 10-12)')], max_length=20)),
                ('is_compulsory', models.BooleanField(default=False, help_text='If true, this subject is automatically assigned to learners of this grade level.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, help_text='If null, the subject is considered a national curriculum subject.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['grade_level', 'name'],
                'unique_together': {('name', 'school')},
            },
        ),
    ]
